[package]
name = "cargo-equip"
version = "0.7.2"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand to bundle your code into one `.rs` file for competitive programming."
repository = "https://github.com/qryxip/cargo-equip"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[dependencies]
anyhow = "1.0.34"
atty = "0.2.14"
cargo_metadata = "0.12.0"
cfg-expr = "0.5.0"
fixedbitset = "0.3.1"
if_chain = "1.0.1"
itertools = "0.9.0"
maplit = "1.0.2"
once_cell = "1.4.1"
proc-macro2 = { version = "1.0.24", features = ["span-locations"] }
quote = "1.0.7"
rand = "0.7.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
shell-escape = "0.1.5"
structopt = "0.3.20"
syn = { version = "1.0.48", features = ["extra-traits", "full", "parsing"] }
tempfile = "3.1.0"
termcolor = "1.1.0"
toml_edit = "0.2.0"
url = "2.1.1"
which = "4.0.2"
xshell = "0.1.6"

[dev-dependencies]
difference = "2.0.0"
