[workspace]
members = ["cargo_equip_marker"]

[package]
name = "cargo-equip"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand to bundle your code into one `.rs` file for competitive programming."
repository = "https://github.com/qryxip/cargo-equip"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[dependencies]
anyhow = "1.0.32"
atty = "0.2.14"
cargo_metadata = "0.11.1"
easy-ext = "0.2.3"
itertools = "0.9.0"
serde = { version = "1.0.115", features = ["derive"] }
structopt = "0.3.17"
termcolor = "1.1.0"
syn = { version = "1.0.39", features = ["full"] }
proc-macro2 = "1.0.19"
maplit = "1.0.2"
