[package]
name = "cargo-equip"
version = "0.17.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand to bundle your code into one `.rs` file for competitive programming."
repository = "https://github.com/qryxip/cargo-equip"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[dependencies]
anyhow = "1.0.41"
arrayvec = { version = "0.7.1", features = ["serde"] }
atty = "0.2.14"
camino = { version = "1.0.4", features = ["serde1"] }
cargo_metadata = "0.13.1"
cfg-expr = "0.7.4"
dirs-next = "2.0.0"
fixedbitset = "0.4.0"
if_chain = "1.0.1"
indoc = "1.0.3"
itertools = "0.10.1"
krates = "0.7.0"
libflate = "1.1.0"
maplit = "1.0.2"
once_cell = "1.8.0"
petgraph = "0.5.1"
prettytable-rs = "0.8.0"
proc-macro2 = { version = "1.0.27", features = ["span-locations"] }
quote = "1.0.9"
rand = "0.8.4"
semver = "0.11.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
shell-escape = "0.1.5"
smol_str = { version = "0.1.18", features = ["serde"] }
spdx = "0.4.1"
structopt = "0.3.21"
syn = { version = "1.0.73", features = ["extra-traits", "full", "parsing", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
toml = "0.5.8"
toml_edit = "0.2.1"
which = "4.1.0"
xshell = "0.1.14"

[dev-dependencies]
difference = "2.0.0"
insta = "1.7.1"
md5 = "0.7.0"
test-case = "1.2.0"
