[package]
name = "cargo-equip"
version = "0.10.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Cargo subcommand to bundle your code into one `.rs` file for competitive programming."
repository = "https://github.com/qryxip/cargo-equip"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[dependencies]
anyhow = "1.0.38"
atty = "0.2.14"
camino = { version = "1.0.3", features = ["serde1"] }
cargo_metadata = "0.13.1"
cfg-expr = "0.7.1"
dirs-next = "2.0.0"
either = "1.6.1"
fixedbitset = "0.3.2"
if_chain = "1.0.1"
itertools = "0.10.0"
krates = "0.7.0"
maplit = "1.0.2"
once_cell = "1.7.2"
prettytable-rs = "0.8.0"
proc-macro2 = { version = "1.0.24", features = ["span-locations"] }
quote = "1.0.9"
rand = "0.8.3"
semver = "0.11.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
shell-escape = "0.1.5"
smol_str = { version = "0.1.17", features = ["serde"] }
spdx = "0.3.6"
structopt = "0.3.21"
syn = { version = "1.0.63", features = ["extra-traits", "full", "parsing", "visit"] }
tempfile = "3.2.0"
termcolor = "1.1.2"
toml = "0.5.8"
toml_edit = "0.2.0"
which = "4.0.2"
xshell = "0.1.9"

[dev-dependencies]
difference = "2.0.0"
